name: Deploy Capstone-Flags to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/build/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'temurin'
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: backend/src/main/resources/static
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: '5.0'
      - name: Build with maven
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: backend-build
          path: backend/target/capstone-flag-game.jar

  deploy-heroku:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: production-heroku
      url: https://y-capstone-project.herokuapp.com/
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: backend-build
          path: backend/target
      - name: Login to heroku
        run: heroku container:login
      - name: Push docker container
        run: heroku container:push web -a y-capstone-project
      - name: Deploy docker container
        run: heroku container:release web -a y-capstone-project